ssh_user             = "debian"
master_ip            = "192.168.1.51"
ssh_private_key_path = "../../common-key/id_rsa_dev"
# certificates_ca_path       = "../../common-key/openssl/ca.pem"
# certificates_etcd_path     = "../../common-key/openssl/etcd.pem"
# certificates_etcd_key_path = "../../common-key/openssl/etcd-key.pem"
